const listaIngles = [
  { pergunta: "Not even", resposta: ["Nem mesmo"] },
  { pergunta: "whisper", resposta: ["sussurro"] },
  { pergunta: "breath", resposta: ["respiração"] },
  { pergunta: "nameless", resposta: ["sem nome"] },
  { pergunta: "anonimos", resposta: ["anônimos"] },
  { pergunta: "dawn", resposta: ["amanhecer"] },
  { pergunta: "embrace", resposta: ["abraçar"] },
  { pergunta: "quiet", resposta: ["silencioso", "tranquilo"] },
  { pergunta: "stillness", resposta: ["imobilidade", "silêncio"] },
  { pergunta: "linger", resposta: ["permanecer"] },
  { pergunta: "stay", resposta: ["ficar"] },
  { pergunta: "remains", resposta: ["restos", "permanece"] },
  { pergunta: "beyond", resposta: ["além"] },
  { pergunta: "hold on", resposta: ["aguente firme", "esperar"] },
  { pergunta: "wait", resposta: ["esperar"] },
  { pergunta: "brings", resposta: ["traz"] },
  { pergunta: "take", resposta: ["levar"] },
  { pergunta: "comes", resposta: ["vem"] },
  { pergunta: "dear", resposta: ["querido"] },
  { pergunta: "may", resposta: ["pode"] },
  { pergunta: "can", resposta: ["pode"] },
  { pergunta: "seem", resposta: ["parecer"] },
  { pergunta: "look", resposta: ["olhar"] },
  { pergunta: "vast", resposta: ["vasto"] },
  { pergunta: "often", resposta: ["frequentemente"] },
  { pergunta: "soul", resposta: ["alma"] },
  { pergunta: "sold", resposta: ["vendido"] },
  { pergunta: "enough", resposta: ["suficiente"] },
  { pergunta: "though", resposta: ["embora"] },
  { pergunta: "through", resposta: ["através"] },
  { pergunta: "speak", resposta: ["falar"] },
  { pergunta: "spark", resposta: ["faísca"] },
  { pergunta: "darkest", resposta: ["mais escuro"] },
  { pergunta: "shine", resposta: ["brilhar"] },
  { pergunta: "bright", resposta: ["brilhante"] },
  { pergunta: "guiding", resposta: ["guiando"] },
  { pergunta: "their", resposta: ["deles", "suas"] },
  { pergunta: "theirs", resposta: ["delas"] },
  { pergunta: "yours", resposta: ["seu"] },
  { pergunta: "gentle", resposta: ["gentil"] },
  { pergunta: "reminding", resposta: ["lembrando"] },
  { pergunta: "step", resposta: ["passo", "etapa"] },
  { pergunta: "refrain", resposta: ["abster-se", "refrão"] },
  { pergunta: "let go", resposta: ["deixar ir", "soltar"] },
  { pergunta: "fears", resposta: ["medos"] },
  { pergunta: "chain", resposta: ["corrente"] },
  { pergunta: "chase", resposta: ["perseguir"] },
  { pergunta: "arms", resposta: ["braços"] },
  { pergunta: "gun", resposta: ["arma"] },
  { pergunta: "stand", resposta: ["ficar de pé"] },
  { pergunta: "keep", resposta: ["manter"] },
  { pergunta: "tall", resposta: ["alto"] },
  { pergunta: "winds", resposta: ["ventos"] },
  { pergunta: "wild", resposta: ["selvagem"] },
  { pergunta: "blow", resposta: ["sopro"] },
  { pergunta: "strength", resposta: ["força"] },
  { pergunta: "grow", resposta: ["crescer"] },
  { pergunta: "rises", resposta: ["ergue-se", "sobe", "nasce"] },
  { pergunta: "born", resposta: ["nascer"] },
  { pergunta: "burn", resposta: ["queimar"] },
  { pergunta: "fail", resposta: ["falhar"] },
  { pergunta: "overcome", resposta: ["superar"] },
  { pergunta: "each", resposta: ["cada"] },
  { pergunta: "every", resposta: ["todo", "cada"] },
  { pergunta: "trail", resposta: ["trilha"] },
  { pergunta: "tear", resposta: ["lágrima"] },
  { pergunta: "earned", resposta: ["ganho", "obtido"] },
  { pergunta: "shot", resposta: ["tiro"] },
  { pergunta: "short", resposta: ["curto"] },
  { pergunta: "chance", resposta: ["chance"] },
  { pergunta: "within", resposta: ["dentro"] },
];
const listaPortugues = [
  { pergunta: "Nem mesmo", resposta: ["Not even"] },
  { pergunta: "sussurro", resposta: ["whisper"] },
  { pergunta: "respiração", resposta: ["breath"] },
  { pergunta: "sem nome", resposta: ["nameless"] },
  { pergunta: "anônimos", resposta: ["anonimos"] },
  { pergunta: "amanhecer", resposta: ["dawn"] },
  { pergunta: "abraçar", resposta: ["embrace"] },
  { pergunta: "silencioso", resposta: ["quiet"] },
  { pergunta: "imobilidade", resposta: ["stillness"] },
  { pergunta: "permanecer", resposta: ["linger"] },
  { pergunta: "ficar", resposta: ["stay"] },
  { pergunta: "além", resposta: ["beyond"] },
  { pergunta: "aguente firme", resposta: ["hold on"] },
  { pergunta: "esperar", resposta: ["wait"] },
  { pergunta: "traz", resposta: ["brings"] },
  { pergunta: "levar", resposta: ["take"] },
  { pergunta: "vem", resposta: ["comes"] },
  { pergunta: "querido", resposta: ["dear"] },
  { pergunta: "pode", resposta: ["may"] },
  { pergunta: "pode", resposta: ["can"] },
  { pergunta: "parecer", resposta: ["seem"] },
  { pergunta: "olhar", resposta: ["look"] },
  { pergunta: "vasto", resposta: ["vast"] },
  { pergunta: "frequentemente", resposta: ["often"] },
  { pergunta: "restos", resposta: ["remains"] },
  { pergunta: "alma", resposta: ["soul"] },
  { pergunta: "suficiente", resposta: ["enough"] },
  { pergunta: "falar", resposta: ["speak"] },
  { pergunta: "faísca", resposta: ["spark"] },
  { pergunta: "através", resposta: ["through"] },
  { pergunta: "mais escuro", resposta: ["darkest"] },
  { pergunta: "brilhar", resposta: ["shine"] },
  { pergunta: "brilhante", resposta: ["bright"] },
  { pergunta: "guiando", resposta: ["guiding"] },
  { pergunta: "deles", resposta: ["their"] },
  { pergunta: "delas", resposta: ["theirs"] },
  { pergunta: "seu", resposta: ["yours"] },
  { pergunta: "gentil", resposta: ["gentle"] },
  { pergunta: "lembrando", resposta: ["reminding"] },
  { pergunta: "passo", resposta: ["step"] },
  { pergunta: "abster-se", resposta: ["refrain"] },
  { pergunta: "deixar ir", resposta: ["let go"] },
  { pergunta: "medos", resposta: ["fears"] },
  { pergunta: "corrente", resposta: ["chain"] },
  { pergunta: "perseguir", resposta: ["chase"] },
  { pergunta: "braços", resposta: ["arms"] },
  { pergunta: "arma", resposta: ["gun"] },
  { pergunta: "ficar de pé", resposta: ["stand"] },
  { pergunta: "manter", resposta: ["keep"] },
  { pergunta: "alto", resposta: ["tall"] },
  { pergunta: "embora", resposta: ["though"] },
  { pergunta: "ventos", resposta: ["winds"] },
  { pergunta: "selvagem", resposta: ["wild"] },
  { pergunta: "sopro", resposta: ["blow"] },
  { pergunta: "força", resposta: ["strength"] },
  { pergunta: "crescer", resposta: ["grow"] },
  { pergunta: "ergue-se", resposta: ["rises"] },
  { pergunta: "nascido", resposta: ["born"] },
  { pergunta: "queimar", resposta: ["burn"] },
  { pergunta: "falhar", resposta: ["fail"] },
  { pergunta: "superar", resposta: ["overcome"] },
  { pergunta: "cada", resposta: ["each"] },
  { pergunta: "todo", resposta: ["every"] },
  { pergunta: "trilha", resposta: ["trail"] },
  { pergunta: "lágrima", resposta: ["tear"] },
  { pergunta: "ganho", resposta: ["earned"] },
  { pergunta: "tiro", resposta: ["shot"] },
  { pergunta: "curto", resposta: ["short"] },
  { pergunta: "chance", resposta: ["chance"] },
  { pergunta: "dentro", resposta: ["within"] },
  { pergunta: "vendido", resposta: ["sold"] },
];
